NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME="SITEHUB"
ORG_URL="https://sitehub.website"
ORG_LOGO="https://sitehub.website/images/sitehub.png"
ORG_DESCRIPTION="Tokens hosted on GitHub | Trade with XLM on Stellar Network"
ORG_OFFICIAL_EMAIL="support@sitehub.website"

[[CURRENCIES]]
code="SITEHUB"
issuer="GALTNG3CZYBV3Z5N5OBHRCHYF6W5AZUXIH5T3U65QJVUC5OGRR5SUCAM"
name="SITEHUB"
image="https://sitehub.website/images/SITEHUB.jpg"
status="live"

[[CURRENCIES]]
code="DIGIHUB"
issuer="GALTNG3CZYBV3Z5N5OBHRCHYF6W5AZUXIH5T3U65QJVUC5OGRR5SUCAM"
name="DIGIHUB"
image="https://sitehub.website/images/DIGIHUB.jpg"
status="live"

[[CURRENCIES]]
code="HUBNET"
issuer="GALTNG3CZYBV3Z5N5OBHRCHYF6W5AZUXIH5T3U65QJVUC5OGRR5SUCAM"
name="HUBNET"
image="https://sitehub.website/images/HUBNET.jpg"
status="live"

[[CURRENCIES]]
code="HUBCOIN"
issuer="GALTNG3CZYBV3Z5N5OBHRCHYF6W5AZUXIH5T3U65QJVUC5OGRR5SUCAM"
name="HUBCOIN"
image="https://sitehub.website/images/HUBCOIN.jpg"
status="live"

[[CURRENCIES]]
code="HUBTECH"
issuer="GALTNG3CZYBV3Z5N5OBHRCHYF6W5AZUXIH5T3U65QJVUC5OGRR5SUCAM"
name="HUBTECH"
image="https://sitehub.website/images/HUBTECH.jpg"
status="live"

[[CURRENCIES]]
code="REALHUB"
issuer="GALTNG3CZYBV3Z5N5OBHRCHYF6W5AZUXIH5T3U65QJVUC5OGRR5SUCAM"
name="REALHUB"
image="https://sitehub.website/images/REALHUB.jpg"
status="live"

[[CURRENCIES]]
code="GITHUB"
issuer="GALTNG3CZYBV3Z5N5OBHRCHYF6W5AZUXIH5T3U65QJVUC5OGRR5SUCAM"
name="GITHUB"
image="https://sitehub.website/images/GITHUB.jpg"
status="live"

[[CURRENCIES]]
code="USBHUB"
issuer="GALTNG3CZYBV3Z5N5OBHRCHYF6W5AZUXIH5T3U65QJVUC5OGRR5SUCAM"
name="USBHUB"
image="https://sitehub.website/images/USBHUB.jpg"
status="live"
