VERSION="2.5.0"

[DOCUMENTATION]
ORG_NAME="Sitehub"
ORG_URL="https://sitehub.website"
ORG_LOGO="https://sitehub.website/images/sitehub.png"
ORG_DESCRIPTION="Tokens hosted on GitHub | Trade with XLM on Stellar Network"
ORG_OFFICIAL_EMAIL="support@sitehub.website"

[[CURRENCIES]]
code="SITEHUB"
issuer="GALTNG3CZYBV3Z5N5OBHRCHYF6W5AZUXIH5T3U65QJVUC5OGRR5SUCAM"
name="SiteHub"
image="https://sitehub.website/images/sitehub.png"
status="live"

[[CURRENCIES]]
code="DIGIHUB"
issuer="GALTNG3CZYBV3Z5N5OBHRCHYF6W5AZUXIH5T3U65QJVUC5OGRR5SUCAM"
name="DigiHub"
image="https://sitehub.website/images/sitehub.png"
status="live"

[[CURRENCIES]]
code="HUBNET"
issuer="GALTNG3CZYBV3Z5N5OBHRCHYF6W5AZUXIH5T3U65QJVUC5OGRR5SUCAM"
name="HubNet"
image="https://sitehub.website/images/sitehub.png"
status="live"

[[CURRENCIES]]
code="HUBCOIN"
issuer="GALTNG3CZYBV3Z5N5OBHRCHYF6W5AZUXIH5T3U65QJVUC5OGRR5SUCAM"
name="HubCoin"
image="https://sitehub.website/images/sitehub.png"
status="live"

[[CURRENCIES]]
code="HUBTECH"
issuer="GALTNG3CZYBV3Z5N5OBHRCHYF6W5AZUXIH5T3U65QJVUC5OGRR5SUCAM"
name="HubTech"
image="https://sitehub.website/images/sitehub.png"
status="live"

[[CURRENCIES]]
code="REALHUB"
issuer="GALTNG3CZYBV3Z5N5OBHRCHYF6W5AZUXIH5T3U65QJVUC5OGRR5SUCAM"
name="RealHub"
image="https://sitehub.website/images/sitehub.png"
status="live"

[[CURRENCIES]]
code="GITHUB"
issuer="GALTNG3CZYBV3Z5N5OBHRCHYF6W5AZUXIH5T3U65QJVUC5OGRR5SUCAM"
name="GitHub"
image="https://sitehub.website/images/sitehub.png"
status="live"

[[CURRENCIES]]
code="USBHUB"
issuer="GALTNG3CZYBV3Z5N5OBHRCHYF6W5AZUXIH5T3U65QJVUC5OGRR5SUCAM"
name="USBHub"
image="https://sitehub.website/images/sitehub.png"
status="live"
